---
- name: "Build, Push, and Run a Docker Container on AlmaLinux"
  hosts: 129.213.47.42
  become: true
  tasks:
    - name: Ensure Docker is installed
      dnf:
        name: docker
        state: present

    - name: Ensure Docker is started and enabled
      service:
        name: docker
        state: started
        enabled: true

    - name: Build Docker image using the Dockerfile
      command: docker build -t triple3a/comingsoon-page .
      args:
        chdir: /path/to/your/dockerfile

    - name: Push image to DockerHub
      command: docker push triple3a/comingsoon-page

    - name: Stop and remove any existing container named web-container (if exists)
      command: docker rm -f web-container
      ignore_errors: true

    - name: Run container with IP binding
      command: docker run -d --name web-container -p 5000:80 triple3a/comingsoon-page
