---
- name: "Build a container with ansible"
  hosts: localhost
  connection: local
  tasks:
    - name: Build Docker image using the Dockerfile
      command: docker build -t triple3a/comingsoon-page .

   
    - name: Push image to DockerHub
      command: docker push triple3a/comingsoon-page

    - name: Run container
      command: docker run -d --name web-container -p 5000:80 triple3a/comingsoon-page
